const GT_ORES_VEIN = {
	naquadah_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 30,
		layer: "ENDSTONE",
		heightRangeUniform: [10, 90],
		generator: "veinedVeinGenerator",
		rareBlockChance: 0.25,
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	pitchblende_vein_end: {
		clusterSize: [32, 40],
		density: 1.0,
		weight: 30,
		layer: "ENDSTONE",
		heightRangeUniform: [30, 60],
		generator: "veinedVeinGenerator",
		rareBlockChance: 0.33,
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	banded_iron_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 30,
		layer: "NETHERRACK",
		heightRangeUniform: [20, 40],
		generator: "veinedVeinGenerator",
		rareBlockChance: 0.075,
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	tetrahedrite_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 70,
		layer: "NETHERRACK",
		heightRangeUniform: [80, 120],
		generator: "veinedVeinGenerator",
		rareBlockChance: 0.15,
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	cassiterite_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 80,
		layer: "STONE",
		heightRangeUniform: [10, 80],
		generator: "veinedVeinGenerator",
		rareBlockChance: 0.33,
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	copper_tin_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 50,
		layer: "STONE",
		heightRangeUniform: [-10, 160],
		generator: "veinedVeinGenerator",
		rareBlockChance: 0.05,
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	iron_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 120,
		layer: "STONE",
		heightRangeUniform: [-10, 60],
		generator: "veinedVeinGenerator",
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
	copper_vein: {
		clusterSize: [40, 52],
		density: 1.0,
		weight: 80,
		layer: "DEEPSLATE",
		heightRangeUniform: [-40, 10],
		generator: "veinedVeinGenerator",
		veininessThreshold: 0.01,
		maxRichnessThreshold: 0.175,
		minRichness: 0.7,
		maxRichness: 1.0,
		edgeRoundoffBegin: 3,
		maxEdgeRoundoff: 0.1,
	},
};
