#Speed of the vanilla minecart.
#"1.2" is vanilla default maximum speed. High speeds will probably derail the cart.
#Default: 1.2
#Range: 0.5 ~ 20.0
minecartMaxSpeed = 3.0
#Height of the heart and armor bar offset.
#Default: 0
#Range: -50 ~ 50
leftBarHeightOffset = 6
#Height of the food bar offset.
#Default: 0
#Range: -50 ~ 50
rightBarHeightOffset = 6
#Whether to allow the nether portal from building
#"False" disables forming.
#Default: true
allowNetherPortalForming = false
#Whether to generate large ore nodes.
#"False" disables the carver-ores.
#Default: true
generateLargeOreNodes = true
#Whether to mute and disable the narrator onboarding on first startup.
#"True" disables the Narrator.
#default: true
disableAccessibilityOnboardingScreen = true

