const GT_OW_VEINS = [
	{
		name: "apatite_vein",
		weight: 100,
		minH: 40,
		maxH: 180,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "cassiterite_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "coal_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "copper_tin_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "copper_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "diamond_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "galena_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "garnet_tin_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "garnet_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "iron_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "lapis_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "lubricant_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "magnetite_vein_ow",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "manganese_vein_ow",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "mica_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "mineral_sand_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "nether_quartz_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "nickel_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "oilsands_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "olivine_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "redstone_vein_ow",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "salts_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "sapphire_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
];

const GT_END_VEINS = [
	{
		name: "bauxite_vein_end",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "magnetite_vein_end",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "naquadah_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "pitchblende_vein_end",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "scheelite_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "sheldonite_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
];

const GT_NETHER_VEINS = [
	{
		name: "banded_iron_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "beryllium_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "certus_quartz",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "manganese_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "molybdenum_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "monazite_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "nether_quartz_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "redstone_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "saltpeter_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "sulfur_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "tetrahedrite_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
	{
		name: "topaz_vein",
		weight: 100,
		minH: 0,
		maxH: 50,
		heightRangeType: "uniform",
		clusterSize: 40,
		density: 0.5,
		layer: "stone",
		biomes: "#c:is_overworld",
	},
];
