const GT_ORES_LAYER = {
	bauxite_vein_end: {
		clusterSize: [32, 40],
		density: 0.3,
		weight: 40,
		layer: "ENDSTONE",
		heightRangeUniform: [10, 80],
		generator: "layeredVeinGenerator",
	},
	magnetite_vein_end: {
		clusterSize: [38, 44],
		density: 0.15,
		weight: 30,
		layer: "ENDSTONE",
		heightRangeUniform: [20, 80],
		generator: "layeredVeinGenerator",
	},
	sheldonite_vein: {
		clusterSize: [25, 29],
		density: 0.2,
		weight: 10,
		layer: "ENDSTONE",
		heightRangeUniform: [5, 50],
		generator: "layeredVeinGenerator",
	},
	certus_quartz: {
		clusterSize: [25, 29],
		density: 0.25,
		weight: 40,
		layer: "NETHERRACK",
		heightRangeUniform: [80, 120],
		generator: "layeredVeinGenerator",
	},
	molybdenum_vein: {
		clusterSize: [25, 29],
		density: 0.25,
		weight: 5,
		layer: "NETHERRACK",
		heightRangeUniform: [20, 50],
		generator: "layeredVeinGenerator",
	},
	monazite_vein: {
		clusterSize: [25, 29],
		density: 0.25,
		weight: 30,
		layer: "NETHERRACK",
		heightRangeUniform: [20, 40],
		generator: "layeredVeinGenerator",
	},
	nether_quartz_vein: {
		clusterSize: [32, 40],
		density: 0.2,
		weight: 80,
		layer: "NETHERRACK",
		heightRangeUniform: [40, 80],
		generator: "layeredVeinGenerator",
	},
	redstone_vein: {
		clusterSize: [32, 40],
		density: 0.2,
		weight: 60,
		layer: "NETHERRACK",
		heightRangeUniform: [5, 40],
		generator: "layeredVeinGenerator",
	},
	saltpeter_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 40,
		layer: "NETHERRACK",
		heightRangeUniform: [5, 45],
		generator: "layeredVeinGenerator",
	},
	sulfur_vein: {
		clusterSize: [32, 40],
		density: 0.2,
		weight: 100,
		layer: "NETHERRACK",
		heightRangeUniform: [10, 30],
		generator: "layeredVeinGenerator",
	},
	topaz_vein: {
		clusterSize: [25, 29],
		density: 0.25,
		weight: 70,
		layer: "NETHERRACK",
		heightRangeUniform: [80, 120],
		generator: "layeredVeinGenerator",
	},
	apatite_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 40,
		layer: "STONE",
		heightRangeUniform: [10, 80],
		generator: "layeredVeinGenerator",
	},
	coal_vein: {
		clusterSize: [38, 44],
		density: 0.25,
		weight: 80,
		layer: "STONE",
		heightRangeUniform: [10, 140],
		generator: "layeredVeinGenerator",
	},
	galena_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 40,
		layer: "STONE",
		heightRangeUniform: [-15, 45],
		generator: "layeredVeinGenerator",
	},
	garnet_tin_vein: {
		clusterSize: [32, 40],
		density: 0.4,
		weight: 80,
		layer: "STONE",
		heightRangeUniform: [30, 60],
		generator: "layeredVeinGenerator",
	},
	lubricant_vein: {
		clusterSize: [25, 29],
		density: 0.25,
		weight: 40,
		layer: "STONE",
		heightRangeUniform: [0, 50],
		generator: "layeredVeinGenerator",
	},
	magnetite_vein_ow: {
		clusterSize: [38, 44],
		density: 0.15,
		weight: 80,
		layer: "STONE",
		heightRangeUniform: [10, 60],
		generator: "layeredVeinGenerator",
	},
	mineral_sand_vein: {
		clusterSize: [32, 40],
		density: 0.2,
		weight: 80,
		layer: "STONE",
		heightRangeUniform: [15, 60],
		generator: "layeredVeinGenerator",
	},
	nickel_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 40,
		layer: "STONE",
		heightRangeUniform: [-10, 60],
		generator: "layeredVeinGenerator",
	},
	salts_vein: {
		clusterSize: [32, 40],
		density: 0.2,
		weight: 50,
		layer: "STONE",
		heightRangeUniform: [30, 70],
		generator: "layeredVeinGenerator",
	},
	oilsands_vein: {
		clusterSize: [25, 29],
		density: 0.3,
		weight: 40,
		layer: "STONE",
		heightRangeUniform: [30, 80],
		generator: "layeredVeinGenerator",
	},
	diamond_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 40,
		layer: "DEEPSLATE",
		heightRangeUniform: [-65, -30],
		generator: "layeredVeinGenerator",
	},
	mica_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 20,
		layer: "DEEPSLATE",
		heightRangeUniform: [-40, -10],
		generator: "layeredVeinGenerator",
	},
	olivine_vein: {
		clusterSize: [32, 40],
		density: 0.25,
		weight: 20,
		layer: "DEEPSLATE",
		heightRangeUniform: [-20, 10],
		generator: "layeredVeinGenerator",
	},
	redstone_vein_ow: {
		clusterSize: [32, 40],
		density: 0.2,
		weight: 60,
		layer: "DEEPSLATE",
		heightRangeUniform: [-65, -10],
		generator: "layeredVeinGenerator",
	},
	sapphire_vein: {
		clusterSize: [25, 29],
		density: 0.25,
		weight: 60,
		layer: "DEEPSLATE",
		heightRangeUniform: [-40, 0],
		generator: "layeredVeinGenerator",
	},
};
