            - name: mrpack-upload
  # You may pin to the exact commit or the version.
  # uses: Warped-Modding/mrpack-upload@352d23960ed382438cf39fd803c70c8bade09f55
  uses: Warped-Modding/mrpack-upload@0.0.9
  with:
    # 
    name: 
    # 
    version-number: 
    # 
    project-id: 
    # 
    pack-filename: 
    # 
    game-versions: 
    # 
    loaders: 
    # 
    modrinth-token: 
